Added Ephemeral Execute with Tag option
carbynestack/cli pull request #18
Opened 2022-03-15 15:31 UTC by grafjo

cli part for https://github.com/carbynestack/ephemeral/pull/17

2022-04-21 10:00 UTC, grafjo commented
@sbckr have rebased to current workflow files

2022-04-21 13:17 UTC, sbckr commented on src/main/java/io/carbynestack/cli/client/ephemeral/command/ExecuteEphemeralClientCliCommandRunner.java
> +    Future<Either<ActivationError, List<ActivationResult>>> execute;
I would rather call it execution, but that is a personal preference.

2022-04-21 13:28 UTC, sbckr commented on src/test/java/io/carbynestack/cli/client/ephemeral/EphemeralClientCliTest.java
> +    try {
I am aware that the existing tests for exceptions were all implemented with try/catch, but I would prefer the transition to Assert.assertThrows. Like

```java
CsCliRunnerException actualCCRE = Assert.assertThrows(CsCliRunnerException.class, () ->
      getCliWithArgs(
              ExecuteEphemeralClientCliCommandConfig.COMMAND_NAME,
              "-i",
              uuid,
              "-f",
              tagFilter,
              "app.example.com")
          .parse());
    assertEquals(actualCCRE.getMessage(),
            EPHEMERAL_CLI_MESSAGES.getString("execute.failure.both-inputs-provided"));
```

2022-04-21 13:30 UTC, sbckr requested changes
PR is missing dependency update for the Ephemeral java client (pom file) which requires https://github.com/carbynestack/ephemeral/pull/17 to be merged

2022-05-11 10:31 UTC, sbckr commented
I have just realised, that the newly added option is not yet described in the readme`. (see [README.md#usage](https://github.com/carbynestack/cli#usage)).

So far we have inserted the respective help output at the corresponding place

2022-05-11 10:31 UTC, sbckr commented
I have just realised, that the newly added option is not yet described in the readme`. (see [README.md#usage](https://github.com/carbynestack/cli#usage)).

So far we have inserted the respective help output at the corresponding place

2022-12-12 09:00 UTC, strieflin commented
Needs to be addressed in a holistic way (see carbynestack/amphora#34).

2022-12-12 09:00 UTC, closed without merging